export const ActionTypes = {
    LOAD_USER: 'LOAD_USER',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    CHANGE_MEAL_AMOUNT: 'CHANGE_MEAL_AMOUNT',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
}
